name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Eksekusi Perintah SSH ke VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e # PENTING: Menghentikan proses jika ada error

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:/usr/local/bin:/usr/bin

            cd /home/devlanding/filantropi_lp/filantropi-main
            
            # 1. Ambil data terbaru dari GitHub tanpa mengubah file
            git fetch origin
            
            # 2. Paksa sinkronisasi: Timpa semua file di VPS agar 100% sama dengan branch main di GitHub
            git reset --hard origin/main
            
            # 3. Lanjut install dan build
            npm install
            npm run build
            
            # 4. Reload aplikasi dengan Zero Downtime
            pm2 reload "Filantropi LP" --update-env || pm2 start node_modules/next/dist/bin/next --name "Filantropi LP" -i max -- start -p 3005
            pm2 save